config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  get 'setup', to: 'setup#dashboard', as: 'setup_dashboard'

  resources :custom_objects do
    resources :custom_fields
    resources :custom_records, only: [:index, :new, :create]
  end

  # Health check route
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/custom_field.rb
class CustomField < ApplicationRecord
  belongs_to :custom_object

  validates :name, presence: true
  validates :field_type, presence: true
end

app/models/custom_object.rb
class CustomObject < ApplicationRecord
    has_many :custom_fields, dependent: :destroy
    has_many :custom_records, dependent: :destroy
  end
  

app/models/custom_record.rb
class CustomRecord < ApplicationRecord
  belongs_to :custom_object

  validates :data, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_custom_objects
  
    private
  
    def set_custom_objects
      @custom_objects = CustomObject.all
    end
  end
  

app/controllers/custom_fields_controller.rb
class CustomFieldsController < ApplicationController
    before_action :set_custom_field, only: [:show, :edit, :update, :destroy]
    before_action :set_custom_object
  
    def index
      @custom_fields = @custom_object.custom_fields
    end
  
    def show
    end
  
    def new
      @custom_field = CustomField.new
    end
  
    def create
      @custom_field = @custom_object.custom_fields.build(custom_field_params)
      if @custom_field.save
        redirect_to [@custom_object, @custom_field], notice: 'Custom field was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @custom_field.update(custom_field_params)
        redirect_to [@custom_object, @custom_field], notice: 'Custom field was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @custom_field.destroy
      redirect_to custom_object_custom_fields_url(@custom_object), notice: 'Custom field was successfully destroyed.'
    end
  
    private
  
    def set_custom_field
      @custom_field = CustomField.find(params[:id])
    end
  
    def set_custom_object
      @custom_object = CustomObject.find(params[:custom_object_id])
    end
  
    def custom_field_params
      params.require(:custom_field).permit(:name, :field_type)
    end
  end
  

app/controllers/custom_objects_controller.rb
class CustomObjectsController < ApplicationController
  before_action :set_custom_object, only: [:show, :edit, :update, :destroy]

  def index
    @custom_objects = CustomObject.all
  end

  def show
  end

  def new
    @custom_object = CustomObject.new
  end

  def create
    @custom_object = CustomObject.new(custom_object_params)
    if @custom_object.save
      redirect_to @custom_object, notice: 'Custom object was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @custom_object.update(custom_object_params)
      redirect_to @custom_object, notice: 'Custom object was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @custom_object.destroy
    redirect_to custom_objects_url, notice: 'Custom object was successfully destroyed.'
  end

  private

  def set_custom_object
    @custom_object = CustomObject.find(params[:id])
  end

  def custom_object_params
    params.require(:custom_object).permit(:name, :description)
  end
end

app/controllers/custom_records_controller.rb
class CustomRecordsController < ApplicationController
    before_action :set_custom_object
  
    def index
      @custom_records = @custom_object.custom_records
    end
  
    def new
      @custom_record = CustomRecord.new
    end
  
    def create
      @custom_record = @custom_object.custom_records.build(custom_record_params)
      if @custom_record.save
        redirect_to custom_object_custom_records_path(@custom_object), notice: 'Custom record was successfully created.'
      else
        render :new
      end
    end
  
    private
  
    def set_custom_object
      @custom_object = CustomObject.find(params[:custom_object_id])
    end
  
    def custom_record_params
      params.require(:custom_record).permit(data: {})
    end
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/setup_controller.rb
class SetupController < ApplicationController
  def dashboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custom_fields_helper.rb
module CustomFieldsHelper
end

app/helpers/custom_objects_helper.rb
module CustomObjectsHelper
end

app/helpers/custom_records_helper.rb
module CustomRecordsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/setup_helper.rb
module SetupHelper
end

app/views/custom_fields/_form.html.erb
<%= form_with(model: [@custom_object, custom_field], local: true) do |form| %>
    <% if custom_field.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(custom_field.errors.count, "error") %> prohibited this custom_field from being saved:</h2>
        <ul>
          <% custom_field.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :field_type %>
      <%= form.text_field :field_type %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>  

app/views/custom_fields/edit.html.erb
<h1>Edit Custom Field</h1>
<%= render 'form', custom_field: @custom_field %>
<%= link_to 'Back', custom_object_custom_fields_path(@custom_object) %>

app/views/custom_fields/index.html.erb
<h1>Custom Fields</h1>
<%= link_to 'New Custom Field', new_custom_object_custom_field_path(@custom_object) %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Field Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @custom_fields.each do |custom_field| %>
      <tr>
        <td><%= custom_field.name %></td>
        <td><%= custom_field.field_type %></td>
        <td><%= link_to 'Show', [@custom_object, custom_field] %></td>
        <td><%= link_to 'Edit', edit_custom_object_custom_field_path(@custom_object, custom_field) %></td>
        <td><%= link_to 'Destroy', [@custom_object, custom_field], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back to Custom Object', @custom_object %>

app/views/custom_fields/new.html.erb
<h1>New Custom Field</h1>
<%= render 'form', custom_field: @custom_field %>
<%= link_to 'Back', custom_object_custom_fields_path(@custom_object) %>

app/views/custom_fields/show.html.erb
<h1><%= @custom_field.name %></h1>
<p>Field Type: <%= @custom_field.field_type %></p>

<%= link_to 'Edit', edit_custom_object_custom_field_path(@custom_object, @custom_field) %> |
<%= link_to 'Back to Custom Object', @custom_object %>

app/views/custom_objects/_form.html.erb
<%= form_with(model: custom_object, local: true) do |form| %>
    <% if custom_object.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(custom_object.errors.count, "error") %> prohibited this custom_object from being saved:</h2>
        <ul>
          <% custom_object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/custom_objects/edit.html.erb
<h1>Edit Custom Object</h1>
<%= render 'form', custom_object: @custom_object %>
<%= link_to 'Back', custom_objects_path %>

app/views/custom_objects/index.html.erb
<h1>Custom Objects</h1>
<%= link_to 'New Custom Object', new_custom_object_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @custom_objects.each do |custom_object| %>
      <tr>
        <td><%= custom_object.name %></td>
        <td><%= custom_object.description %></td>
        <td><%= link_to 'Show', custom_object %></td>
        <td><%= link_to 'Edit', edit_custom_object_path(custom_object) %></td>
        <td><%= link_to 'Destroy', custom_object, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/custom_objects/new.html.erb
<h1>New Custom Object</h1>
<%= render 'form', custom_object: @custom_object %>
<%= link_to 'Back', custom_objects_path %>

app/views/custom_objects/show.html.erb
<h1><%= @custom_object.name %></h1>
<p><%= @custom_object.description %></p>

<h2>Fields</h2>
<%= link_to 'New Field', new_custom_object_custom_field_path(@custom_object) %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Field Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @custom_object.custom_fields.each do |custom_field| %>
      <tr>
        <td><%= custom_field.name %></td>
        <td><%= custom_field.field_type %></td>
        <td><%= link_to 'Show', [@custom_object, custom_field] %></td>
        <td><%= link_to 'Edit', edit_custom_object_custom_field_path(@custom_object, custom_field) %></td>
        <td><%= link_to 'Destroy', [@custom_object, custom_field], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Records</h2>
<%= link_to 'New Record', new_custom_object_custom_record_path(@custom_object) %>

<table>
  <thead>
    <tr>
      <th>Data</th>
    </tr>
  </thead>
  <tbody>
    <% @custom_object.custom_records.each do |custom_record| %>
      <tr>
        <td><%= custom_record.data %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_custom_object_path(@custom_object) %> |
<%= link_to 'Back', custom_objects_path %>

app/views/custom_records/index.html.erb
<h1>Custom Records</h1>
<%= link_to 'New Custom Record', new_custom_object_custom_record_path(@custom_object) %>

<table>
  <thead>
    <tr>
      <th>Data</th>
    </tr>
  </thead>
  <tbody>
    <% @custom_records.each do |custom_record| %>
      <tr>
        <td><%= custom_record.data %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back to Custom Object', @custom_object %>

app/views/custom_records/new.html.erb
<h1>New Custom Record</h1>
<%= form_with(model: [@custom_object, @custom_record], local: true) do |form| %>
  <% if @custom_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@custom_record.errors.count, "error") %> prohibited this custom_record from being saved:</h2>
      <ul>
        <% @custom_record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_area :data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back to Custom Object', @custom_object %>

app/views/home/index.html.erb
<h1>Welcome to Hubbubb</h1>
<p>Your platform for managing and scripting business data.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hubbubb</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <nav class="navbar">
    <ul>
      <li class="dropdown">
        <a href="javascript:void(0)" class="dropbtn">Custom Objects</a>
        <div class="dropdown-search">
          <div class="search-container">
            <input type="text" id="searchInput" placeholder="Search objects..">
          </div>
          <div id="objectList">
            <a href="<%= root_path %>">Home</a>
            <% @custom_objects.each do |object| %>
              <a href="<%= custom_object_path(object) %>"><%= object.name %></a>
            <% end %>
          </div>
        </div>
      </li>
    </ul>
    <ul class="navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="javascript:void(0)" class="dropbtn">Profile</a>
          <div class="dropdown-content">
            <%= link_to 'Edit Profile', edit_user_registration_path %>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
          </div>
        </li>
        <li class="dropdown-icon">
          <a href="javascript:void(0)" class="dropbtn">
            <%= image_tag('gear_icon.png', alt: 'Setup', class: 'gear-icon') %>
          </a>
          <div class="dropdown-content">
            <%= link_to 'Setup', setup_dashboard_path %>
          </div>
        </li>
      <% else %>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Log In', new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>

  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <%= yield %>
</body>
</html>

app/views/setup/dashboard.html.erb
<h1>Setup Dashboard</h1>

<p>Welcome to the setup section. Here you can manage your custom objects and fields.</p>

<h2>Custom Objects</h2>
<%= link_to 'New Custom Object', new_custom_object_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% CustomObject.all.each do |custom_object| %>
      <tr>
        <td><%= custom_object.name %></td>
        <td><%= custom_object.description %></td>
        <td><%= link_to 'Edit', edit_custom_object_path(custom_object) %></td>
        <td><%= link_to 'Destroy', custom_object, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>